version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5434"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
  person-app:
    container_name: person-app
    image: person-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres